import numpy as np
from time import time
a=np.arange(1,10)
print(a)
print(sum(a))
def benchmarks(n):
    t1=time()
    a=list(range(1,n+1))
    tot=sum(a)
    t2=time()
    print('time taken by python is',t2-t1)
    t1=time()
    a1=np.arange(1,n+1)
    tot=np.sum(a1)
    t2=time()
    print('Time taken by numpy is',t2-t1)
benchmarks(10_000_000)
a=np.array([[1,2,3],[10,20,30],[0,0,-1]])
print(a)
a=np.arange(1,20)
print(a)
a=np.linspace(0,1.0,num=5)
print(a)
a=np.linspace(0,1.0,num=6)
print(a)
a=np.linspace(1,5,num=5,dtype=np.int16)
print(a)
a=np.empty((2,2))
print(a)
a=np.eye(4)
print(a)
a=np.ones((3,3))
print(a)
a=np.ones((2,2,3))
print(a)
a=np.ones(6,dtype=np.bool)
print(a)
a=np.zeros((3,3))
print(a)
a=np.zeros((2,3,3))
print(a)